openapi: 3.0.0
info:
  title: Push API
  version: 1.0.0
  description: 푸시 및 알림 API
servers:
  - url: http://220.90.208.217:8080
tags:
  - name: Push
    description: Push 보내기, Push 설정
  - name: Notification
    description: 알림
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /push/admin:
    post:
      tags:
        - Push
      summary: 관리자 push
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                token:
                  - >-
                    dKz7V3QcRDq9qHyobwki1N:APA91bHbs_ymFN4ZTzCENb5y-SVUYV2Gd7nrnswsPAzXCNgiP19TdAPhLcrVKIxtWZfleMSMTCNsEFbbTDxNvP2ZBfND9BC7EpWexvDVIArUczFVp6WVZYusVY5CZtVteyrlj5FqAI1k
                category: admin
                title: push title
                body: push body
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: admin push sent
  /push/category:
    post:
      tags:
        - Push
      summary: 항목별 push
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                category: notice
                title: test push title
                body: test push body
      responses:
        '200':
          description: Successful response
  /push/config/add/token:
    post:
      tags:
        - Push
      summary: 새로운 FCM 토큰 추가
      parameters:
        - name: token
          in: query
          schema:
            type: string
          example: >-
            dKz7V3QcRDq9qHyobwki1N:APA91bHbs_ymFN4ZTzCENb5y-SVUYV2Gd7nrnswsPAzXCNgiP19TdAPhLcrVKIxtWZfleMSMTCNsEFbbTDxNvP2ZBfND9BC7EpWexvDVIArUczFVp6WVZYusVY5CZtVteyrlj5FqAI1k
      responses:
        '200':
          description: Successful response
  /push/config/add/user:
    post:
      tags:
        - Push
      summary: FCM 토큰과 유저 연결
      security:
        - bearerAuth: []
      parameters:
        - name: token
          in: query
          schema:
            type: string
          example: >-
            dKz7V3QcRDq9qHyobwki1N:APA91bHbs_ymFN4ZTzCENb5y-SVUYV2Gd7nrnswsPAzXCNgiP19TdAPhLcrVKIxtWZfleMSMTCNsEFbbTDxNvP2ZBfND9BC7EpWexvDVIArUczFVp6WVZYusVY5CZtVteyrlj5FqAI1k
      responses:
        '200':
          description: Successful response
  /push/config:
    get:
      tags:
        - Push
      summary: push 알림 설정
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                global: 'Y'
                notice: 'Y'
                inquiry: 'Y'
                content: 'Y'
  /push/config/edit:
    put:
      tags:
        - Push
      summary: push 알림 설정
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                category: notice
                value: 'N'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples:
                example-0:
                  summary: global
                example-1:
                  summary: notice
                example-2:
                  summary: inquiry
                example-3:
                  summary: content
  /notification/list:
    get:
      tags:
        - Notification
      summary: 알림 목록
      security:
        - bearerAuth: []
      parameters:
        - name: token
          in: query
          schema:
            type: string
          example: >-
            dKz7V3QcRDq9qHyobwki1N:APA91bHbs_ymFN4ZTzCENb5y-SVUYV2Gd7nrnswsPAzXCNgiP19TdAPhLcrVKIxtWZfleMSMTCNsEFbbTDxNvP2ZBfND9BC7EpWexvDVIArUczFVp6WVZYusVY5CZtVteyrlj5FqAI1k
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 8
                  userUuid: bc03c6ec-0ac5-431e-a6ca-f77578795131
                  token: >-
                    dKz7V3QcRDq9qHyobwki1N:APA91bHbs_ymFN4ZTzCENb5y-SVUYV2Gd7nrnswsPAzXCNgiP19TdAPhLcrVKIxtWZfleMSMTCNsEFbbTDxNvP2ZBfND9BC7EpWexvDVIArUczFVp6WVZYusVY5CZtVteyrlj5FqAI1k
                  read: 'N'
                  category: admin
                  title: push title 1
                  timestamp: '2021-11-25T06:00:08.222+00:00'
                - id: 9
                  userUuid: bc03c6ec-0ac5-431e-a6ca-f77578795131
                  token: >-
                    dKz7V3QcRDq9qHyobwki1N:APA91bHbs_ymFN4ZTzCENb5y-SVUYV2Gd7nrnswsPAzXCNgiP19TdAPhLcrVKIxtWZfleMSMTCNsEFbbTDxNvP2ZBfND9BC7EpWexvDVIArUczFVp6WVZYusVY5CZtVteyrlj5FqAI1k
                  read: 'N'
                  category: admin
                  title: push title 2
                  timestamp: '2021-11-30T06:00:08.222+00:00'
                - id: 10
                  userUuid: bc03c6ec-0ac5-431e-a6ca-f77578795131
                  token: >-
                    dKz7V3QcRDq9qHyobwki1N:APA91bHbs_ymFN4ZTzCENb5y-SVUYV2Gd7nrnswsPAzXCNgiP19TdAPhLcrVKIxtWZfleMSMTCNsEFbbTDxNvP2ZBfND9BC7EpWexvDVIArUczFVp6WVZYusVY5CZtVteyrlj5FqAI1k
                  read: 'N'
                  category: notice
                  title: push title notice
                  timestamp: '2021-11-31T06:00:08.222+00:00'
  /notification/read:
    put:
      tags:
        - Notification
      summary: 알림 읽음
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          example: '29'
      responses:
        '200':
          description: Successful response
  /notification/readall:
    put:
      tags:
        - Notification
      summary: 알림 모두 읽음
      parameters:
        - name: ids
          in: query
          schema:
            type: string
          example: 30,31,32
      responses:
        '200':
          description: Successful response